apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-monitoring-app-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name:  monitoring-app
        image: jerinpaul/monitoring:latest  
        ports:
        - containerPort: 5000  

---
apiVersion: v1
kind: Service
metadata:
  name: python-monitoring-app-service
spec:
  selector:
    app: monitoring-app
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5000  
  type: LoadBalancer  
